version: '3.7'
services:
  # -----------------------------------------------
  app:
    build:
      context: ./config
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './app/${APP_DIRECTORY}/:/var/www/'
    networks:
      - flow
    depends_on:
      - nginx
      - mysql
      - redis
  # -----------------------------------------------
  nginx:
    image: 'nginx:1.19.7-alpine'
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    volumes:
      - './app/${APP_DIRECTORY}/:/var/www:delegated'
      - './nginx:/etc/nginx/conf.d'
    ports:
      - '${APP_PORT}:80'
    networks:
      - flow
  # -----------------------------------------------
  redis:
    image: 'redis'
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - flow
  # -----------------------------------------------
  mysql:
    image: 'mysql:8.0'
    container_name: ${PROJECT_NAME}-mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    environment:
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - './.mysql:/var/lib/mysql'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - flow
# -----------------------------------------------
networks:
  flow:
    driver: bridge
# -----------------------------------------------
volumes:
  flow-mysql:
    driver: local
  flow-nginx:
    driver: local
  flow-app:
    driver: local
  flow-redis:
    driver: local
